### ISSUE TITLE
peer-to-peer

### ISSUE THREAD

**Issue by keza681** [keza681/linda-portfolio-part2#10]

**Comment by victorokoroji** [comment]
I think you should consider grouping your images in an image folder so improve the entire structure of your project and make it easier for you to navigate through the different files in your project

**Comment by victorokoroji** [comment]
I believe Your menu on line 49, is a nav-item and as such should be inside the `nav`  element tag and not outside. You should consider moving the menu inside the `nav` tag

**Comment by usorfaitheloho** [comment]
Hi @keza681  👋
I want to want to congratulate you on your work. It looks clean and responsive 🚀

However, I noticed a few issues that may be holding your work from attaining perfection:

-  I think it will make your work look even better if you could make the navbar fixed to the top, and you could also give it a nice border and background.

-  In the works section, the project cards don’t have space between them. Could you add a gap between the cards in the mobile version?

- In the about myself section, the text of the languages is not perfectly centered beneath the icons.

- In the contact section, the font properties in the textarea do not perfectly match the one on your chosen Figma design.
- I think you should rename your footer classes based on the section you're working on to enhance readability of your code.

 - I noticed that the mobile menu-overlay keeps showing at the bottom of the desktop page. Please add a media query to make it disappear in the desktop version.



Please feel free to ask for any more clarification about the issues we raised.
Happy Coding 🚀
